### ISSUE TITLE
Must provide DB

### ISSUE THREAD

**Issue by devonwesley** [tradle/asyncstorage-down#9]
<img width="503" alt="screen shot 2018-02-12 at 1 26 37 pm" src="https://user-images.githubusercontent.com/8162708/36120791-26a9b9a6-0ff9-11e8-9b44-d99eebffdee7.png">

<img width="593" alt="screen shot 2018-02-12 at 1 26 50 pm" src="https://user-images.githubusercontent.com/8162708/36120795-2dde5ca4-0ff9-11e8-9415-9679d18ed0f7.png">

<img width="512" alt="screen shot 2018-02-12 at 1 27 02 pm" src="https://user-images.githubusercontent.com/8162708/36120810-36c8156c-0ff9-11e8-9b54-5689bc4c1a5c.png">

Hey hows it going? thank you for providing this wonderful wrapper, Im really happy I found it. I ran into this problem and wondering if anyone can spot what I might be doing wrong thank you in advance.

**Comment by mvayngrib** [comment]
@Jusdev89 the code you pasted works fine for me (levelup 0.18.6, asyncstorage-down 3.1.1). What versions of levelup and asyncstorage-down are you using?

Also, can you check that the imported asyncstoragedown is not undefined?

**Comment by devonwesley** [comment]
@mvayngrib  No im using levelup "^2.0.1" and asyncstorage-down 4.0.1. Is that the problem?

And yes the package  asyncstorage-down returns a function.

Thanks for the rapid response. amazing!

**Comment by mvayngrib** [comment]
@Jusdev89 looking at the level docs it seems their arguments to levelup have changed since v1. It now expects the db implementation as the first arg.

see:
https://www.npmjs.com/package/levelup#usage
https://www.npmjs.com/package/levelup#levelupdb-options-callback

i haven't tested it myself with v2, so let me know if it ends up working. If it does and you're up to updating the README with a blurb/example for levelup v2, that would be great :)

**Comment by devonwesley** [comment]
Hey @mvayngrib just seeing this. Yes let me try that. and id be happy to update the readme accordingly if it works out. Thanks
